### ISSUE TITLE
Not showing download data, only shows upload data 

### ISSUE THREAD

**Issue by thormanj** [aln-1/speedtest-php#4]
I get the same results from example php code or running the file downloaded from compose.

It does not show the download data.

Could you please advise?

![Screen Shot 2022-08-31 at 12 10 14 AM](https://user-images.githubusercontent.com/9053622/187597302-3672d02e-62b9-4993-a43a-680cd91babb7.png)

**Comment by sergeykomlev** [comment]
I fixed this issue and added a proxy support [here](https://github.com/nextpost-tech/speedtest-php).

**Comment by aln-1** [comment]
sorry for the very late reply. I saw your fork, can you identify what is the fix for the problem reported by @thormanj  ?

**Comment by aln-1** [comment]
fixed now
